name: Jikesync
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: user/app:latest
  
    - name: Run job
      run: |
        docker run -e CUBOX_API_KEY="https://cubox.pro/c/api/save/vk3x3kpwebtkol" -e REFRESH_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZEd2czhHWjVtVktvWWx5N3dlb3RzbkJnb0VlTzZFdHRtY1VWXC9nWEhYRFJKTlNjMnExemF4XC8yQnJ6dFo0d0xycXhpaEdHMDFsdEFLVmNvZkRXKzU1alBIWTU3aVJsY1wvRnVtU20rSDVEVlo3eEtvUzBNSVlZQzQ4ZEZtNjlKNkNFVVwvdjRLZERHaXd2ZHlZc0tnN202a0pOSDZMb1BDdm1UY0xiTjltaCtxOD0iLCJ2IjozLCJpdiI6IlNvMUVwQ001WFNGWDd2ZVM5d2tscGc9PSIsImlhdCI6MTY5ODU4NTk3OS4yM30.cl_GVJ2rSMAWUpW_ZoOqNnSy7LWCZ9u8xVJ-pSZrCSA" user/app:latest